<?PHP IF ( ! DEFINED('BASEPATH')) EXIT('NO DIRECT SCRIPT ACCESS ALLOWED');
CLASS Cetak EXTENDS CI_CONTROLLER {
    /*****
     | LAPORAN PDF DENGAN DOMPDF
     | CONTROLLER CLAPORANPDF
     | BY GTECH
    *****/
 
    PUBLIC FUNCTION __CONSTRUCT() {
        PARENT::__CONSTRUCT();
        $THIS->LOAD->MODEL('M_cetak');
        $THIS->LOAD->LIBRARY('Dompdf_lib.php');
    }
 
    PUBLIC FUNCTION INDEX()
    {
        $DATA['TITLE'] = 'LAPORAN PEMENANG'; //JUDUL TITLE
        $DATA['pemenang'] = $THIS->M_cetak->GETALLITEM(); //QUERY MODEL SEMUA BARANG
        //$THIS->LOAD->VIEW('VLAPORAN',$DATA);
    }
 
    // FUNGSI CETAK PDF
    PUBLIC FUNCTION cetakpdf(){
        $DATA['TITLE'] = 'CETAK PDF BARANG'; //JUDUL TITLE
        $DATA['pemenang'] = $THIS->M_cetak->GETALLITEM(); //QUERY MODEL SEMUA BARANG
 
        //$THIS->LOAD->VIEW('VCETAKLAPORAN', $DATA);
 
        $PAPER_SIZE  = 'A4'; //PAPER SIZE
        $ORIENTATION = 'LANDSCAPE'; //TIPE FORMAT KERTAS
        $HTML = $THIS->OUTPUT->GET_OUTPUT();
 
        $THIS->DOMPDF->SET_PAPER($PAPER_SIZE, $ORIENTATION);
        //CONVERT TO PDF
        $THIS->DOMPDF->LOAD_HTML($HTML);
        $THIS->DOMPDF->RENDER();
        $THIS->DOMPDF->STREAM("LAPORAN.PDF", ARRAY('ATTACHMENT'=>0));
    }
}
/* END OF FILE CLAPORANPDF.PHP */
/* LOCATION: ./APPLICATION/CONTROLLERS/CLAPORANPDF.PHP */